from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime, time


class CanvasAuthRequest(BaseModel):
    """Canvas authentication request"""
    canvas_url: str = Field(..., description="Canvas institution URL (e.g., https://institution.instructure.com)")
    access_token: str = Field(..., description="Canvas API access token")


class GoogleAuthRequest(BaseModel):
    """Google OAuth authentication request"""
    credentials: dict = Field(..., description="Google OAuth credentials")


class Assignment(BaseModel):
    """Canvas assignment model"""
    id: int
    title: str
    description: Optional[str] = None
    due_date: Optional[datetime] = None
    course_name: str
    course_id: int
    assignment_type: Optional[str] = "assignment"
    points: Optional[float] = None
    estimated_time: Optional[int] = None  # in minutes
    category: Optional[str] = None  # quick_task, medium_effort, long_project, major_project
    submission_types: Optional[List[str]] = []
    html_url: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "id": 12345,
                "title": "Math Problem Set 3",
                "description": "Complete problems 1-15 from Chapter 4",
                "due_date": "2025-11-15T23:59:00",
                "course_name": "Calculus II",
                "course_id": 101,
                "assignment_type": "problem_set",
                "points": 100.0,
                "estimated_time": 180
            }
        }


class UserPreferences(BaseModel):
    """User study preferences"""
    study_session_length: int = Field(default=90, description="Preferred study session length in minutes")
    break_frequency: int = Field(default=25, description="Break frequency in minutes (Pomodoro style)")
    daily_study_hours: int = Field(default=4, description="Maximum daily study hours")
    preferred_study_times: List[str] = Field(
        default=["09:00-12:00", "14:00-17:00", "19:00-21:00"],
        description="Preferred time blocks for studying"
    )
    buffer_days: int = Field(default=1, description="Days before due date to finish")
    weekend_study: bool = Field(default=True, description="Whether to schedule study sessions on weekends")
    
    class Config:
        json_schema_extra = {
            "example": {
                "study_session_length": 90,
                "break_frequency": 25,
                "daily_study_hours": 4,
                "preferred_study_times": ["09:00-12:00", "14:00-17:00"],
                "buffer_days": 1,
                "weekend_study": True
            }
        }


class StudyTask(BaseModel):
    """Individual study task generated by AI"""
    task_name: str
    assignment_title: str
    course_name: str
    duration_minutes: int
    suggested_date: str  # ISO format date
    suggested_start_time: str  # HH:MM format
    priority: str = "medium"  # high, medium, low
    description: Optional[str] = None
    course_id: Optional[int] = None
    assignment_id: Optional[int] = None

    class Config:
        json_schema_extra = {
            "example": {
                "task_name": "Review Chapter 4 concepts",
                "assignment_title": "Math Problem Set 3",
                "course_name": "Calculus II",
                "duration_minutes": 60,
                "suggested_date": "2025-11-10",
                "suggested_start_time": "14:00",
                "priority": "high",
                "description": "Review key formulas and example problems before starting problem set"
            }
        }


class StudyPlan(BaseModel):
    """Complete study plan generated by AI"""
    tasks: List[StudyTask]
    total_study_time: int  # in minutes
    generated_at: datetime = Field(default_factory=datetime.now)
    plan_summary: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "tasks": [],
                "total_study_time": 360,
                "generated_at": "2025-11-08T10:00:00",
                "plan_summary": "Study plan covering 3 assignments over 5 days"
            }
        }


class CalendarEventResponse(BaseModel):
    """Google Calendar event response"""
    event_id: str
    summary: str
    start_time: datetime
    end_time: datetime
    description: Optional[str] = None
    html_link: Optional[str] = None
    status: str = "confirmed"

    class Config:
        json_schema_extra = {
            "example": {
                "event_id": "abc123xyz",
                "summary": "Study: Math Problem Set 3",
                "start_time": "2025-11-10T14:00:00",
                "end_time": "2025-11-10T15:00:00",
                "description": "Review Chapter 4 concepts",
                "html_link": "https://calendar.google.com/calendar/event?eid=abc123xyz",
                "status": "confirmed"
            }
        }


class ErrorResponse(BaseModel):
    """Standard error response"""
    detail: str
    timestamp: datetime = Field(default_factory=datetime.now)
    error_code: Optional[str] = None

    class Config:
        json_schema_extra = {
            "example": {
                "detail": "Failed to fetch assignments",
                "timestamp": "2025-11-08T10:00:00",
                "error_code": "CANVAS_API_ERROR"
            }
        }
